<?php 

$_category = $this->getCurrentCategory();
$_helper    = $this->helper('catalog/output');
$header_check = $_helper->categoryAttribute($_category, $_category->getEnhancedCategoryImage(),'enhanced_category_image');

if($header_check && strlen($header_check) > 1)
{
	
	$header_image_path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "catalog/category/". $header_check;
	$header_heading = $_helper->categoryAttribute($_category, $_category->getEnhancedCategoryHeading(),'enhanced_category_heading');
	$header_content = $_helper->categoryAttribute($_category, $_category->getEnhancedCategoryTopContent(),'enhanced_category_top_content');
	$header_content = $header_content && strlen($header_content) > 0 ? $header_content : $_category->getDescription();
	if($header_content && $header_content == strip_tags($header_content))
	{
			$header_array = explode("\n\r",$header_content);
			$header_content = "";
			for($i = 0; $i < count($header_array); $i++)
			{
				$header_content .= "<p>".$header_array[$i]."</p>";
			}
			
	}
	
    $_headerCTA = $this->getJcf('enhanced_category_top_cta');
	$header_image_url = $this->helper('timage')->init($header_image_path)->resize(585,null,true);

?><style>


div.brand_page_container.maincontainer div.brand_container_part1 div.txt div.innertxt.ptxt p { width: 100%; } 



@media only screen and (max-width: 767px) { 

	div.brand_page_container.maincontainer div.brand_container_part1 { display: block }
	div.brand_page_container.maincontainer div.shop_by_treatment div.boxes div.box { margin: 0 0 20px 0 }
	div.brand_page_container.maincontainer div.brand_container_part1 div.txt { padding: 15px }

}

@media only screen and (min-width: 768px) { 

	div.brand_page_container.maincontainer div.brand_container_part1 div.txt { padding: 40px }
    div.brand_page_container.maincontainer div.brand_container_part1 { margin-bottom: 15px }

}
</style>


	<div class="ec brand_container_part1">
		<div class="img">
			<img src="<?php echo $header_image_url; ?>" />
		</div>
		<div class="txt">
			<div class="title">
				<h1 class="custom-font">
				<?php echo $header_heading; ?>
				</h1>
			</div>
			<div class="innertxt ptxt">
				<?php echo $header_content; ?>			
<?php 

			if($_headerCTA && count($_headerCTA) > 0 && $_headerCTA[0]["text"])
			 {
				$_link = "Read More";
				$_hiddenText = "";
				echo '<p class="ptxt2">'; 
				if($_headerCTA[0]["url"]) {
				echo "<a href=\"{$_headerCTA[0]["url"]}\" class=\"custom-bg know_more\">" ;
					
					$_link = $_headerCTA[0]["text"]  ? $_headerCTA[0]["text"] : $_link;
					
				}
				else 
				{
					echo "<a id=\"cat_read_more\" class=\"custom-bg know_more\" href=\"#\">";
					$_hiddenText = "<div id=\"cat_more_content\" style=\"display:none\" class=\"innertxt\">".$_headerCTA[0]["text"]."</div>";
					
				}
				echo $_link."</a></p>".$_hiddenText;
			 
			 }
?>
			</div>
		</div>
	</div>
	
<?php }